// Created by Pysics on 2017.5.3

'use strict'

export const FETCH_ETC_DATA_REQUEST = "FETCH_ETC_DATA_REQUEST"
export const FETCH_ETC_DATA_SUCCESS = "FETCH_ETC_DATA_SUCCESS"
export const FETCH_ETC_DATA_FAILURE = "FETCH_ETC_DATA_FAILURE"

export const LOGIN_AUTH_REQUEST = "LOGIN_AUTH_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const FETCH_MESSAGE_REQUEST = "FETCH_MESSAGE_REQUEST"
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS"
export const FETCH_MESSAGE_FAILURE = "FETCH_MESSAGE_FAILURE"